let body = JSON.parse($response.body); 
body.can_upgrade_to_better_ai = true;
body.can_upgrade_to_pro = false;
body.has_active_subscription = true;
body.has_running_subscription = true;
body.eligible_for_application_settings = true;
body.any_organization_has_running_subscription = false;
body.has_better_ai = true;
body.eligible_for_cloud_sync = true;
body.any_organization_has_better_ai = false;
body.any_organization_has_active_subscription = false;
body.eligible_for_pro_features = true;
body = JSON.stringify(body);
$done({body});